module.exports = {
    registerUser: require('./register-user'),
    authenticate: require('./authenticate-user'),
    retrieveUser: require('./retrieve-user'),
    retrieveLatestPosts: require('./retrieve-latest-posts'),
    retrieveCompleteUser: require('./retrieve-complete-user'),
    toggleLikePost: require('./toggle-like-post'),
    retrievePost: require('./retrieve-post'),
    sendComment : require('./send-comment'),
    retrieveConnections: require('./retrieve-connections'),
    removeSkillItem: require('./remove-skill-item'),
    createSkillItem: require('./create-skill-item'),
    createExperienceItem: require('./create-experience-item'),
    removeExperienceItem: require('./remove-experience-item'),
    retrievePersonalInfo: require('./retrieve-personal-info'),
    updateUser: require('./update-user'),
    updateProfileImage: require('./update-profile-image'),
    retrieveUserPosts: require('./retrieve-user-posts'),
    createPost: require('./create-post'),
    retrieveChats: require('./retrieve-chats'),
    retrieveChat: require('./retrieve-chat'),
    createChat: require('./create-chat'),
    sendMessage: require('./send-message'),
    retrieveSummaryUser: require('./retrieve-summary-user'),
    search: require('./search'),
    checkFriendRequest: require('./check-friend-requests'),
    retrieveFriendRequests: require('./retrieve-friends-requests'),
    retrieveNews: require('./retrieve-news'),
    removeNews: require('./remove-news'),
    removeConnection: require('./remove-connection'),
    retrieveFriendConnections: require('./retrieve-friend-connections'),
    areThereNews: require('./are-there-news')
}